name: Build

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:

      # Checkout the code.
    - name: Checkout
      uses: actions/checkout@v3

      # Install the dependencies.
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install xsltproc
        sudo apt install libxml2-utils
        sudo apt install librsvg2-bin

      # Compile the graphs at daily resolution.
    - name: Compile dailies
      run: make -C daily

      # Compile the graphs at hourly resolution.
    - name: Compile hourlies
      run: make -C hourly

      # Create the release ID from the repo name and version tag.
    - name: Release - get ID
      id: get-id
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        project=$(echo "${{github.repository}}" | cut -d/ -f2)
        version=$(echo "${{github.ref_name}}" | sed 's/^v//')
        echo "::set-output name=id::${project}-${version}"

      # Package the release artifacts.
    - name: Release - package artifacts
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        mkdir ${{steps.get-id.outputs.id}}
        mv hourly/png ${{steps.get-id.outputs.id}}/hourly
        mv daily/png  ${{steps.get-id.outputs.id}}/daily
        tar cvzf ${{steps.get-id.outputs.id}}.tar.gz ${{steps.get-id.outputs.id}}

      # Create a release.
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        name: ${{steps.get-id.outputs.id}}
        files: |
          ${{steps.get-id.outputs.id}}.tar.gz
